spring.application.name=product-service

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka

server.port=0



#The address to which Spring Boot will send traces.
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
# Sampling rate of requests.
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
